# site settings
title: Odedia's Corner
subtitle: by Oded Shopen
email: odedia@gmail.com
description: These are my thoughts, rants and geeky projects
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://www.odedia.org
author: Oded Shopen
street_address: Israel
city: Israel
country: Israel

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 500

# social settings
500px_url: https://500px.com/odedia
github_url: https://www.github.com/odedia
linkedin_url: https://www.linkedin.com/in/odedia/
twitter_url: https://twitter.com/odedia
pivotal_url: https://content.pivotal.io/authors/oded-shopen


# build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-paginate-v2
#Pagination Settings
pagination:
  enabled: true
  per_page: 2
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
permalink: /:year/:month/:title.html

