# site settings
title: Odedia's Corner
subtitle: by Oded Shopen
email: odedia@gmail.com
description: Oded's thoughts, rants and geeky projects
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://www.odedia.org
author: Oded Shopen
street_address: Israel
city: Israel
country: Israel

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: https://500px.com/odedia
github_url: https://www.github.com/odedia
linkedin_url: https://www.linkedin.com/in/odedia/
twitter_url: https://twitter.com/odedia

# build settings
markdown: kramdown
sass:
  style: compressed
